package swing;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import dao.dao_customer;
import models.m_customer;

public class Customer_edit extends javax.swing.JFrame {

    String param, iden;
    
    /**
     * Creates new form Customer_add
     * @param id
     */
    public Customer_edit(String id) {
        initComponents();
        jPanel1.setFocusable(true);
        
        param = id;
        customer_tampil();
    }
    
    public Customer_edit() {
        initComponents();
        jPanel1.setFocusable(true);
    }
    
    void customer_tampil() {
        try {
            dao_customer dao = new dao_customer();
            List<m_customer> data = dao.readCustomer();

            for (m_customer d : data) {
                if (d.getIdCustomer().equals(param)) {
                    edit_txt_ktp.setText(d.getNoKtp());
                    edit_txt_nama.setText(d.getNama());
                    edit_txt_kontak.setText(d.getKontak());
                    edit_txt_alamat.setText(d.getAlamat());
                    iden = d.getNama().toLowerCase();
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    void customer_edit(String ktp, String nama, String kontak, String alamat) {
        try {
            dao_customer dao = new dao_customer();
            m_customer data = new m_customer();
            String date = new SimpleDateFormat("dd/MM/yyyy").format(new Date());

            data.setIdCustomer(param);
            data.setNoKtp(ktp);
            data.setNama(nama);
            data.setKontak(kontak);
            data.setAlamat(alamat);
            data.setEditedAt(date);

            if (dao.editCustomer(data)) {
                JOptionPane.showMessageDialog(null, "Data berhasil tersimpan!", "Berhasil", JOptionPane.INFORMATION_MESSAGE);

                edit_txt_ktp.setText("");
                edit_txt_nama.setText("");
                edit_txt_kontak.setText("");
                edit_txt_alamat.setText("");

                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Maaf, data gagal tersimpan!", "Gagal", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menyimpan data!\n" + e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    void customer_reset() {
        try {
            dao_customer dao = new dao_customer();
            m_customer data = new m_customer();
            String date = new SimpleDateFormat("dd/MM/yyyy").format(new Date());

            if (iden.contains(" ")) {
                iden = iden.substring(0, iden.indexOf(" "));
            }

            data.setIdCustomer(param);
            data.setUsername(iden);
            data.setPassword(iden);
            data.setEditedAt(date);

            if (dao.resetKaryawan(data)) {
                JOptionPane.showMessageDialog(null, "Password berhasil diubah!", "Berhasil", JOptionPane.INFORMATION_MESSAGE);

                edit_txt_ktp.setText("");
                edit_txt_nama.setText("");
                edit_txt_kontak.setText("");
                edit_txt_alamat.setText("");

                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Maaf, password gagal diubah!", "Gagal", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mengubah data!\n" + e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        edit_txt_ktp = new javax.swing.JTextField();
        edit_txt_nama = new javax.swing.JTextField();
        edit_txt_alamat = new javax.swing.JTextField();
        edit_btn_simpan = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        edit_txt_kontak = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        edit_btn_reset = new javax.swing.JPanel();
        jLabel74 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit customer");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Edit customer");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(96, 96, 96));
        jLabel2.setText("Pastikan nomor KTP customer sudah benar");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Data diri customer");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(93, 93, 93));
        jLabel4.setText("Nomor KTP");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(93, 93, 93));
        jLabel5.setText("Nama lengkap");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(93, 93, 93));
        jLabel7.setText("Alamat");

        edit_txt_ktp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edit_txt_ktp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96), 2));

        edit_txt_nama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edit_txt_nama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96), 2));

        edit_txt_alamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edit_txt_alamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96), 2));
        edit_txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_txt_alamatActionPerformed(evt);
            }
        });

        edit_btn_simpan.setBackground(new java.awt.Color(0, 120, 215));
        edit_btn_simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit_btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_btn_simpanMouseClicked(evt);
            }
        });

        jLabel73.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Simpan data");

        javax.swing.GroupLayout edit_btn_simpanLayout = new javax.swing.GroupLayout(edit_btn_simpan);
        edit_btn_simpan.setLayout(edit_btn_simpanLayout);
        edit_btn_simpanLayout.setHorizontalGroup(
            edit_btn_simpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_btn_simpanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel73)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        edit_btn_simpanLayout.setVerticalGroup(
            edit_btn_simpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel73, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        edit_txt_kontak.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edit_txt_kontak.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96), 2));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(93, 93, 93));
        jLabel6.setText("Kontak");

        edit_btn_reset.setBackground(new java.awt.Color(204, 204, 204));
        edit_btn_reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit_btn_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_btn_resetMouseClicked(evt);
            }
        });

        jLabel74.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(51, 51, 51));
        jLabel74.setText("Reset password");

        javax.swing.GroupLayout edit_btn_resetLayout = new javax.swing.GroupLayout(edit_btn_reset);
        edit_btn_reset.setLayout(edit_btn_resetLayout);
        edit_btn_resetLayout.setHorizontalGroup(
            edit_btn_resetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_btn_resetLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel74)
                .addGap(15, 15, 15))
        );
        edit_btn_resetLayout.setVerticalGroup(
            edit_btn_resetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel74, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(edit_btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edit_txt_alamat)
                            .addComponent(edit_txt_nama)
                            .addComponent(edit_txt_ktp, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(edit_btn_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edit_txt_kontak))))
                .addGap(40, 40, 40))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {edit_txt_alamat, edit_txt_ktp, edit_txt_nama});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(edit_txt_ktp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(edit_txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(edit_txt_kontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(edit_txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edit_btn_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edit_btn_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {edit_txt_alamat, edit_txt_kontak, edit_txt_ktp, edit_txt_nama});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edit_txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_txt_alamatActionPerformed

    private void edit_btn_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_btn_resetMouseClicked
        int selection = JOptionPane.showConfirmDialog(null, "Reset password akun?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (selection == JOptionPane.OK_OPTION) {
            customer_reset();
        }
    }//GEN-LAST:event_edit_btn_resetMouseClicked

    private void edit_btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_btn_simpanMouseClicked
        String ktp = edit_txt_ktp.getText(), nama = edit_txt_nama.getText(), kontak = edit_txt_kontak.getText(), alamat = edit_txt_alamat.getText();

        if (ktp.isEmpty() || nama.isEmpty() || kontak.isEmpty() || alamat.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Mohon lengkapi data!", "Peringatan", JOptionPane.ERROR_MESSAGE);

            if (ktp.isEmpty()) {
                edit_txt_ktp.requestFocus();
            } else if (nama.isEmpty()) {
                edit_txt_nama.requestFocus();
            } else if (kontak.isEmpty()) {
                edit_txt_kontak.requestFocus();
            } else if (alamat.isEmpty()) {
                edit_txt_alamat.requestFocus();
            }
        } else {
            int selection = JOptionPane.showConfirmDialog(null, "Simpan perubahan?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (selection == JOptionPane.OK_OPTION) {
                customer_edit(ktp, nama, kontak, alamat);
            }
        }
    }//GEN-LAST:event_edit_btn_simpanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel edit_btn_reset;
    private javax.swing.JPanel edit_btn_simpan;
    private javax.swing.JTextField edit_txt_alamat;
    private javax.swing.JTextField edit_txt_kontak;
    private javax.swing.JTextField edit_txt_ktp;
    private javax.swing.JTextField edit_txt_nama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
