/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.awt.GraphicsEnvironment;

/**
 *
 * @author dgeda
 */
public class Trans_pinjam extends javax.swing.JFrame {

    /**
     * Creates new form Trans_pinjam
     */
    public Trans_pinjam() {
        initComponents();
        jLabel4.setText("<html>Pastikan kamu sudah memasukkan data pelanggan dengan benar dan <br>periksa semua VCD yang disewa ada di keranjang<html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        peminjaman = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        pinjam_txt_booking = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        pinjam_txt_deadline = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        pinjam_txt_customer = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        pinjam_txt_cari = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_pinjam_data = new javax.swing.JTable();
        pinjam_btn_tambah = new javax.swing.JPanel();
        jLabel90 = new javax.swing.JLabel();
        pinjam_btn_tambah1 = new javax.swing.JPanel();
        jLabel91 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        pinjam_txt_bayar = new javax.swing.JTextField();
        pinjam_txt_harga = new javax.swing.JTextField();
        pinjam_btn_proses = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_pinjam_keranjang = new javax.swing.JTable();
        jLabel68 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transaksi peminjaman");
        setBackground(new java.awt.Color(255, 255, 255));

        peminjaman.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Transaksi peminjaman");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(96, 96, 96));
        jLabel4.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit.");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel66.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(51, 51, 51));
        jLabel66.setText("Data transaksi");

        jLabel70.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(93, 93, 93));
        jLabel70.setText("No. Transaksi");

        pinjam_txt_booking.setEditable(false);
        pinjam_txt_booking.setBackground(new java.awt.Color(244, 244, 244));
        pinjam_txt_booking.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pinjam_txt_booking.setText("P0001");
        pinjam_txt_booking.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(213, 213, 213), 2));

        jLabel72.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(93, 93, 93));
        jLabel72.setText("Jatuh tempo");

        pinjam_txt_deadline.setEditable(false);
        pinjam_txt_deadline.setBackground(new java.awt.Color(244, 244, 244));
        pinjam_txt_deadline.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pinjam_txt_deadline.setText("29/06/2020");
        pinjam_txt_deadline.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(213, 213, 213), 2));

        jLabel71.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(93, 93, 93));
        jLabel71.setText("Customer");

        pinjam_txt_customer.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pinjam_txt_customer.setText("C0001");
        pinjam_txt_customer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96), 2));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"C0001", "Rehuel Paskahrio H"}
            },
            new String [] {
                "ID", "Nama"
            }
        ));
        jScrollPane4.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(50);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        pinjam_txt_cari.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pinjam_txt_cari.setText("V0001-002");
        pinjam_txt_cari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96), 2));

        jLabel76.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(93, 93, 93));
        jLabel76.setText("Cari");

        tb_pinjam_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"V0001", "Spider-Man: Far from Home", "15000.00"}
            },
            new String [] {
                "ID VCD", "JUDUL", "HARGA"
            }
        ));
        jScrollPane1.setViewportView(tb_pinjam_data);
        if (tb_pinjam_data.getColumnModel().getColumnCount() > 0) {
            tb_pinjam_data.getColumnModel().getColumn(0).setMinWidth(100);
            tb_pinjam_data.getColumnModel().getColumn(0).setMaxWidth(100);
            tb_pinjam_data.getColumnModel().getColumn(2).setMinWidth(50);
            tb_pinjam_data.getColumnModel().getColumn(2).setMaxWidth(50);
        }

        pinjam_btn_tambah.setBackground(new java.awt.Color(204, 204, 204));
        pinjam_btn_tambah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        pinjam_btn_tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel90.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel90.setText("Tambah");

        javax.swing.GroupLayout pinjam_btn_tambahLayout = new javax.swing.GroupLayout(pinjam_btn_tambah);
        pinjam_btn_tambah.setLayout(pinjam_btn_tambahLayout);
        pinjam_btn_tambahLayout.setHorizontalGroup(
            pinjam_btn_tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pinjam_btn_tambahLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel90)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pinjam_btn_tambahLayout.setVerticalGroup(
            pinjam_btn_tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinjam_btn_tambahLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel90)
                .addGap(3, 3, 3))
        );

        pinjam_btn_tambah1.setBackground(new java.awt.Color(204, 204, 204));
        pinjam_btn_tambah1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        pinjam_btn_tambah1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel91.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel91.setText("Cari");

        javax.swing.GroupLayout pinjam_btn_tambah1Layout = new javax.swing.GroupLayout(pinjam_btn_tambah1);
        pinjam_btn_tambah1.setLayout(pinjam_btn_tambah1Layout);
        pinjam_btn_tambah1Layout.setHorizontalGroup(
            pinjam_btn_tambah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pinjam_btn_tambah1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel91)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pinjam_btn_tambah1Layout.setVerticalGroup(
            pinjam_btn_tambah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinjam_btn_tambah1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel91)
                .addGap(3, 3, 3))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("QTY");

        jTextField1.setText("2");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(93, 93, 93), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel72)
                            .addGap(20, 20, 20)
                            .addComponent(pinjam_txt_deadline))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel70)
                            .addGap(15, 15, 15)
                            .addComponent(pinjam_txt_booking, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel66))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel71)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(pinjam_txt_customer, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))))
                .addGap(30, 30, 30)
                .addComponent(jLabel76)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pinjam_txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pinjam_btn_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pinjam_btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel66)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel70)
                    .addComponent(pinjam_txt_booking, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pinjam_txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel76)
                    .addComponent(pinjam_btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pinjam_btn_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel72)
                            .addComponent(pinjam_txt_deadline, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel71)
                            .addComponent(pinjam_txt_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel69.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(51, 51, 51));
        jLabel69.setText("Keranjang dan pembayaran");

        jLabel74.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(93, 93, 93));
        jLabel74.setText("Total harga");

        jLabel75.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(93, 93, 93));
        jLabel75.setText("Harga bayar");

        pinjam_txt_bayar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pinjam_txt_bayar.setText("30000");
        pinjam_txt_bayar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96), 2));
        pinjam_txt_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinjam_txt_bayarActionPerformed(evt);
            }
        });

        pinjam_txt_harga.setEditable(false);
        pinjam_txt_harga.setBackground(new java.awt.Color(244, 244, 244));
        pinjam_txt_harga.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pinjam_txt_harga.setText("30000.00");
        pinjam_txt_harga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(213, 213, 213), 2));

        pinjam_btn_proses.setBackground(new java.awt.Color(0, 120, 215));

        jLabel73.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Simpan transaksi");

        javax.swing.GroupLayout pinjam_btn_prosesLayout = new javax.swing.GroupLayout(pinjam_btn_proses);
        pinjam_btn_proses.setLayout(pinjam_btn_prosesLayout);
        pinjam_btn_prosesLayout.setHorizontalGroup(
            pinjam_btn_prosesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinjam_btn_prosesLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel73)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        pinjam_btn_prosesLayout.setVerticalGroup(
            pinjam_btn_prosesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pinjam_btn_prosesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel73)
                .addContainerGap())
        );

        tb_pinjam_keranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"V0001", "Spider-Man: Far from Home", "2", "30000.00"}
            },
            new String [] {
                "ID VCD", "VCD", "JUMLAH", "HARGA TOTAL"
            }
        ));
        jScrollPane2.setViewportView(tb_pinjam_keranjang);
        if (tb_pinjam_keranjang.getColumnModel().getColumnCount() > 0) {
            tb_pinjam_keranjang.getColumnModel().getColumn(0).setMinWidth(100);
            tb_pinjam_keranjang.getColumnModel().getColumn(0).setMaxWidth(100);
            tb_pinjam_keranjang.getColumnModel().getColumn(3).setMinWidth(100);
            tb_pinjam_keranjang.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        jLabel68.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(96, 96, 96));
        jLabel68.setText("Klik data pada tabel untuk menghapus dari keranjang");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel69)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel75)
                    .addComponent(jLabel74))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pinjam_txt_bayar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pinjam_txt_harga, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pinjam_btn_proses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel68)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel69)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel74)
                            .addComponent(pinjam_txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel75)
                            .addComponent(pinjam_txt_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(pinjam_btn_proses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 41, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel68)))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout peminjamanLayout = new javax.swing.GroupLayout(peminjaman);
        peminjaman.setLayout(peminjamanLayout);
        peminjamanLayout.setHorizontalGroup(
            peminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peminjamanLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(peminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(peminjamanLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(peminjamanLayout.createSequentialGroup()
                        .addGroup(peminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45))))
        );
        peminjamanLayout.setVerticalGroup(
            peminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peminjamanLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pinjam_txt_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinjam_txt_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinjam_txt_bayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trans_pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trans_pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trans_pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trans_pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trans_pinjam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel peminjaman;
    private javax.swing.JPanel pinjam_btn_proses;
    private javax.swing.JPanel pinjam_btn_tambah;
    private javax.swing.JPanel pinjam_btn_tambah1;
    private javax.swing.JTextField pinjam_txt_bayar;
    private javax.swing.JTextField pinjam_txt_booking;
    private javax.swing.JTextField pinjam_txt_cari;
    private javax.swing.JTextField pinjam_txt_customer;
    private javax.swing.JTextField pinjam_txt_deadline;
    private javax.swing.JTextField pinjam_txt_harga;
    private javax.swing.JTable tb_pinjam_data;
    private javax.swing.JTable tb_pinjam_keranjang;
    // End of variables declaration//GEN-END:variables
}
