package swing;

import dao.dao_customer;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import models.m_customer;

public class Trans_pinjam_cari extends javax.swing.JFrame {

    String p_customer = "", log_karyawan;
    Boolean cari = false;

    /**
     * Creates new form Trans_pinjam_cari
     */
    public Trans_pinjam_cari(String id) {
        initComponents();
        log_karyawan = id;
        customer_tampil();
    }

    public Trans_pinjam_cari() {
        initComponents();
    }

    void customer_tampil() {
        Object[] baris = {"ID", "NAMA", "NOMOR KTP"};
        DefaultTableModel dt = new DefaultTableModel(null, baris);
        pinjam_tabel.setModel(dt);

        try {
            dao_customer dao = new dao_customer();
            List<m_customer> data = dao.readCustomer();

            for (m_customer d : data) {
                String[] isi = {d.getIdCustomer(), d.getNama(), d.getNoKtp()};
                dt.addRow(isi);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal mendapatkan data\n" + e, "Gagal", JOptionPane.ERROR_MESSAGE);
        }
    }

    void tb_customer_cari(String query) {
        try {
            cari = true;
            DefaultTableModel model = (DefaultTableModel) pinjam_tabel.getModel();
            TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
            pinjam_tabel.setRowSorter(tr);
            tr.setRowFilter(RowFilter.regexFilter(query));
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    void tb_customer_klik() {
        int row = pinjam_tabel.getSelectedRow();
        p_customer = pinjam_tabel.getModel().getValueAt(row, 0).toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pinjam_cari = new javax.swing.JTextField();
        pinjam_refresh = new javax.swing.JButton();
        pinjam_daftar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pinjam_tabel = new javax.swing.JTable();
        pinjam_lanjut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Pilih Customer");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(96, 96, 96));
        jLabel2.setText("Jika customer berlum terdaftar, daftar dulu melalui tombol daftar");

        pinjam_cari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pinjam_cari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96), 2));
        pinjam_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pinjam_cariKeyReleased(evt);
            }
        });

        pinjam_refresh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pinjam_refresh.setText("Refresh");
        pinjam_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinjam_refreshActionPerformed(evt);
            }
        });

        pinjam_daftar.setText("Daftar");
        pinjam_daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinjam_daftarActionPerformed(evt);
            }
        });

        pinjam_tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        pinjam_tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pinjam_tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pinjam_tabel);

        pinjam_lanjut.setText("Lanjut");
        pinjam_lanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinjam_lanjutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pinjam_refresh)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(pinjam_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pinjam_lanjut)
                                .addGap(10, 10, 10)
                                .addComponent(pinjam_daftar)))
                        .addGap(40, 40, 40))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(pinjam_daftar)
                    .addComponent(pinjam_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pinjam_lanjut))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(pinjam_refresh)
                .addGap(40, 40, 40))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pinjam_cari, pinjam_daftar, pinjam_lanjut, pinjam_refresh});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pinjam_daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinjam_daftarActionPerformed
        Customer_add tambah = new Customer_add();
        tambah.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pinjam_daftarActionPerformed

    private void pinjam_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinjam_refreshActionPerformed
        DefaultTableModel dataModel;
        if (cari) {
            dataModel = (DefaultTableModel) this.pinjam_tabel.getModel();
            dataModel.setRowCount(0);
        }
        customer_tampil();
    }//GEN-LAST:event_pinjam_refreshActionPerformed

    private void pinjam_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinjam_cariKeyReleased
        String query = pinjam_cari.getText();
        tb_customer_cari(query);
    }//GEN-LAST:event_pinjam_cariKeyReleased

    private void pinjam_lanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinjam_lanjutActionPerformed
        if (p_customer.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Mohon pilih customer terlebih dahulu!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        } else {
            Trans_pinjam pinjam = new Trans_pinjam(log_karyawan, p_customer);
            pinjam.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_pinjam_lanjutActionPerformed

    private void pinjam_tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinjam_tabelMouseClicked
        tb_customer_klik();
    }//GEN-LAST:event_pinjam_tabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trans_pinjam_cari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trans_pinjam_cari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trans_pinjam_cari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trans_pinjam_cari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trans_pinjam_cari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pinjam_cari;
    private javax.swing.JButton pinjam_daftar;
    private javax.swing.JButton pinjam_lanjut;
    private javax.swing.JButton pinjam_refresh;
    private javax.swing.JTable pinjam_tabel;
    // End of variables declaration//GEN-END:variables
}
