package swing;

import dao.dao_vcd;
import java.awt.Dimension;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import models.m_vcd;

public class Vcd_edit extends javax.swing.JFrame {

    String param, iden;

    /**
     * Creates new form Customer_add
     *
     * @param id
     */
    public Vcd_edit(String id) {
        initComponents();
        jPanel1.setFocusable(true);
        param = id;
        vcd_tampil();
    }

    private Vcd_edit() {
        initComponents();
        jPanel1.setFocusable(true);
    }

    void vcd_tampil() {
        try {
            dao_vcd dao = new dao_vcd();
            List<m_vcd> data = dao.readVcd();

            for (m_vcd d : data) {
                if (d.getId_vcd().equals(param)) {
                    vcd_edit_judul.setText(d.getJudul());
                    vcd_edit_bahasa.setText(d.getBahasa());
                    vcd_edit_rilis.setText(d.getRilis());
                    vcd_edit_poster.setText(d.getPoster());
                    vcd_edit_genre.setText(d.getGenre());
                    vcd_edit_poster.setPreferredSize(new Dimension(250, 35));
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    void vcd_edit(String judul, String genre, String bahasa, String poster, String id_harga, String rilis) {
        try {
            dao_vcd dao = new dao_vcd();
            m_vcd data = new m_vcd();
            String date = new SimpleDateFormat("dd/MM/yyyy").format(new Date());

            data.setJudul(judul);
            data.setGenre(genre);
            data.setBahasa(bahasa);
            data.setPoster(poster);
            data.setId_harga(id_harga);
            data.setRilis(rilis);
            data.setId_vcd(param);

            if (dao.editVcd(data)) {
                JOptionPane.showMessageDialog(null, "Data berhasil tersimpan!", "Berhasil", JOptionPane.INFORMATION_MESSAGE);

                vcd_edit_judul.setText("");
                vcd_edit_bahasa.setText("");
                vcd_edit_genre.setText("");
                vcd_edit_poster.setText("");
                vcd_edit_rilis.setText("");

                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Maaf, data gagal tersimpan!", "Gagal", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menyimpan data!\n" + e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        vcd_edit_judul = new javax.swing.JTextField();
        vcd_edit_rilis = new javax.swing.JTextField();
        vcd_edit_genre = new javax.swing.JTextField();
        vcd_edit_bahasa = new javax.swing.JTextField();
        vcd_btn_simpan = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        vcd_edit_poster = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit data VCD");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Edit data VCD");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(96, 96, 96));
        jLabel2.setText("Pastikan data VCD sudah benar");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Data VCD");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(93, 93, 93));
        jLabel4.setText("Judul");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(93, 93, 93));
        jLabel5.setText("Tanggal rilis");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(93, 93, 93));
        jLabel6.setText("Genre");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(93, 93, 93));
        jLabel7.setText("Bahasa");

        vcd_edit_judul.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vcd_edit_judul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96), 2));

        vcd_edit_rilis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vcd_edit_rilis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96), 2));

        vcd_edit_genre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vcd_edit_genre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96), 2));

        vcd_edit_bahasa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vcd_edit_bahasa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96), 2));

        vcd_btn_simpan.setBackground(new java.awt.Color(0, 120, 215));
        vcd_btn_simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vcd_btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vcd_btn_simpanMouseClicked(evt);
            }
        });

        jLabel73.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Simpan data");

        javax.swing.GroupLayout vcd_btn_simpanLayout = new javax.swing.GroupLayout(vcd_btn_simpan);
        vcd_btn_simpan.setLayout(vcd_btn_simpanLayout);
        vcd_btn_simpanLayout.setHorizontalGroup(
            vcd_btn_simpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vcd_btn_simpanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel73)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        vcd_btn_simpanLayout.setVerticalGroup(
            vcd_btn_simpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel73, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(93, 93, 93));
        jLabel8.setText("Link poster");

        vcd_edit_poster.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vcd_edit_poster.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96), 2));
        vcd_edit_poster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vcd_edit_posterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vcd_edit_bahasa)
                            .addComponent(vcd_edit_genre)
                            .addComponent(vcd_edit_rilis)
                            .addComponent(vcd_edit_judul, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(vcd_btn_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vcd_edit_poster)))
                    .addComponent(jLabel3))
                .addGap(40, 40, 40))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {vcd_edit_bahasa, vcd_edit_genre, vcd_edit_judul, vcd_edit_rilis});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(vcd_edit_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(vcd_edit_rilis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(vcd_edit_genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(vcd_edit_bahasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(vcd_edit_poster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(vcd_btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {vcd_edit_bahasa, vcd_edit_genre, vcd_edit_judul, vcd_edit_poster, vcd_edit_rilis});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void vcd_edit_posterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vcd_edit_posterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vcd_edit_posterActionPerformed

    private void vcd_btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vcd_btn_simpanMouseClicked
        String judul = vcd_edit_judul.getText(), bahasa = vcd_edit_bahasa.getText(), rilis = vcd_edit_rilis.getText(), poster = vcd_edit_poster.getText(), genre = vcd_edit_genre.getText();
        String id_harga = "H0001";
        if (judul.isEmpty() || bahasa.isEmpty() || rilis.isEmpty() || poster.isEmpty() || genre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Mohon lengkapi data!", "Peringatan", JOptionPane.ERROR_MESSAGE);

            if (judul.isEmpty()) {
                vcd_edit_judul.requestFocus();
            } else if (bahasa.isEmpty()) {
                vcd_edit_bahasa.requestFocus();
            } else if (rilis.isEmpty()) {
                vcd_edit_rilis.requestFocus();
            } else if (genre.isEmpty()) {
                vcd_edit_genre.requestFocus();
            } else if (poster.isEmpty()) {
                vcd_edit_poster.requestFocus();
            }
        } else {
            int selection = JOptionPane.showConfirmDialog(null, "Simpan data?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (selection == JOptionPane.OK_OPTION) {
                vcd_edit(judul, genre, bahasa, poster, id_harga, rilis);
            }
        }
    }//GEN-LAST:event_vcd_btn_simpanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vcd_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vcd_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vcd_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vcd_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vcd_edit().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel vcd_btn_simpan;
    private javax.swing.JTextField vcd_edit_bahasa;
    private javax.swing.JTextField vcd_edit_genre;
    private javax.swing.JTextField vcd_edit_judul;
    private javax.swing.JTextField vcd_edit_poster;
    private javax.swing.JTextField vcd_edit_rilis;
    // End of variables declaration//GEN-END:variables
}
